cleanedwq

diff --git a/launch_builder b/launch_builder
--- a/launch_builder
+++ b/launch_builder
@@ -5,7 +5,7 @@ then
     CALLER_USER=`whoami`  
     uid=$(id -u ${CALLER_USER})
     gid=$(id -g ${CALLER_USER})
-    sudo gid=$gid uid=$uid CALLER_USER=${CALLER_USER} "$0" "$@"
+    sudo gid=$gid uid=$uid CALLER_USER=${CALLER_USER}  WORKSPACE=${WORKSPACE} "$0" "$@"
     exit
 else
     if [ -z "$CALLER_USER" ]
@@ -20,113 +20,181 @@ echo "*** Please ensure user name is added to docker group"
 echo "*** you should be able to start stop docker without sudo"
 #https://medium.com/devgorilla/how-to-install-docker-on-ubuntu-18-04-495216a16092
 
-#TODO
-DOCKER_IMAGE="granjan/vpp-build-env:three"
-
-INSTALLATION_MODE=1
-INSTALLATION_PATH="/usr/bin"
-BUILDER_CREATE="vpp_build_builder_create"
-#This is just temporary
-BUILD_ALL="vpp_build_build_all"
-SCRIPT=$(readlink -f $0)
-BASE_DIR=`dirname $SCRIPT`
-
-VPP_WS="/home/${CALLER_USER}/VPP-WS/"
-VPP_WS_KITCHEN="KITCHEN"
-
-if [ "$BASE_DIR" == "$INSTALLATION_PATH" ]
+#TOD0
+INSTALLATION_PATH="/usr/local/bin/vpp_builder"
+#copy ssh-id and misc
+if [ ! "$(readlink -f $0)" == "$INSTALLATION_PATH" ]
 then
-    INSTALLATION_MODE=0
-else
-    echo 
-    echo "  Files will get installed in $INSTALLATION_PATH"
-    INSTALLATION_MODE=1
-
-    echo "  VPP Build env installation starting ....."
-    echo  
-    echo "  Creating VPP workspace directory @ $VPP_WS"
-    mkdir -p $VPP_WS
-
-    KITCHEN="$VPP_WS/$VPP_WS_KITCHEN"
-    echo
-    echo "  Creating VPP workspace kitchen sink @ $KITCHEN"
-    echo "      This directory will have small scripts"
-    echo "  like toplogy etc dictating topology, vpp configs etc"
-    mkdir -p $KITCHEN
-    chown $uid:$gid $KITCHEN
-    
-    echo   
-    echo "  Copying example build scipts @$KITCHEN "
-    echo "  ---Run vpp_build_one_time_run once for setting maven for honeycomb build"
-    cp  $BASE_DIR/vpp_build_one_time_run $KITCHEN
-    
-    echo "  ---See vpp_build_build_all on how build is done"
-    cp  $BASE_DIR/vpp_build_build_all $KITCHEN
-
-    chown $uid:$gid $VPP_WS
-    chown  $uid:$gid $KITCHEN
-    chown  $uid:$gid $KITCHEN/vpp_build_one_time_run
-    chown  $uid:$gid $KITCHEN/vpp_build_build_all
-    
-    BUILDER_FILE=$INSTALLATION_PATH/$BUILDER_CREATE
-    cp -f $(readlink -f $0) $BUILDER_FILE
-    echo "  ----Please use $BUILDER_FILE for creating build"
-    echo "      deploy env after this installation deploy"
- 
-    #let us fix the username used for docker
-    BUILDER_CONNECT="vpp_build_builder_connect"
-    echo "  ---Use $BUILDER_CONNECT to connect to your build environment"
-    echo "docker exec -u $CALLER_USER -it builder "/bin/bash" "  > $INSTALLATION_PATH/$BUILDER_CONNECT
-    
-    BUILDER_STOP="vpp_build_builder_stop"
-    echo "  ---Use $BUILDER_STOP to stop vpp build env"
-    echo "docker stop builder"  > $INSTALLATION_PATH/$BUILDER_STOP
-
-    BUILDER_RM="vpp_build_builder_rm"
-    echo "  ---Use $BUILDER_STOP to remove vpp build env"
-    echo "docker rm builder"  > $INSTALLATION_PATH/$BUILDER_RM
-
-    chmod +x $INSTALLATION_PATH/vpp_build_builder_*
-    chown -R $uid:$gid $INSTALLATION_PATH/vpp_build_builder_*
-
-    echo "  Pulling Docker image $DOCKER_IMAGE"
-    docker pull $DOCKER_IMAGE
+    echo "  Installing in $(readlink -f $0)   $INSTALLATION_PATH"
+    cp "$(readlink -f $0)"  $INSTALLATION_PATH
     exit
 fi
 
-export VPP_WS=$VPP_WS
+if [ -z $WORKSPACE ];
+then
+	echo "  Please export WORKSPACE directory which has build env as well"
+	exit
+else
+	MOUNT_DIR=$WORKSPACE
+fi
+
+create_builder=0
+start_builder=0
+pause_builder=0
+delete_builder=0
+connect_builder=0
+
+# read the options
+OPTION=`getopt -o cspdhn --long create,start,pause,delete,help,connect -- "$@"`
+eval set -- "$OPTION"
+#Following are the options 
+while true; do
+    case "$1" in
+        -c| --create ) 
+            create_builder=1
+            shift;;
+        -i| --start )
+            start_builder=1
+            shift;;
+        -n|--connect)
+            connect_builder=1
+            shift 1;;
+        -s|--pause) 
+            pause_builder=1 
+            shift;;
+        -d|--delete)
+            delete_builder=1
+            shift;;
+        -h|--help) 
+            echo "Usage"
+            echo "      $0  --create          :Create the builder "   
+            echo "      $0  --start           :Starts the builder "
+            echo "      $0  --connect         :Connect to builder"
+            echo "      $0  --delete          :Delete  the builder "
+            echo "      $0  --pause           :Stop the builder  "
+            exit ;;
+        --) shift ; break ;;
+        *) echo "Internal error!" ; exit 1 ;;
+    esac
+done
+
+remove_container() {
+	#Cleanup all containers on the host (dead or alive).
+	if [ -z "$1" ]; then 
+		echo "Please supply container name"
+        return 1
+	else
+		docker stop $1 > /dev/null 2>&1
+		docker rm $1   > /dev/null 2>&1
+        return 0
+	fi
+}
+
+create_container() {
+        if [ -z "$1" ]; then 
+                echo "Please supply container name"
+        fi
+        export container_name=$1
+        
+        echo "  Removing any build any older build environment"
+        docker stop  $container_name
+        docker rm    $container_name
+        docker run                                          \
+                --privileged                                \
+                -v $MOUNT_DIR:$MOUNT_DIR                    \
+                --name $container_name                      \
+                -u ${NAME}                                  \
+                -v $VPP_DIR:/vpp                            \
+                -v /var/run/docker.sock:/var/run/docker.sock\
+                -td $DOCKER_IMAGE_NAME                      \
+                /bin/bash 
+            
+        echo "  fixing the image ...."
+        docker exec -it $container_name /bin/bash -c "  \
+                        mkdir -p  /home/gyan;           \
+                        touch /etc/passwd;              \
+                        touch /etc/group;               \
+                        groupadd $gid;                  \
+                        hostname $container_name;       \
+                        useradd -rm -d /home/$NAME -s   \
+                        /bin/bash -g $gid  -G sudo  -u  \
+                        $uid $NAME;                     \
+                        chown $uid:$gid /home/$NAME;    \
+                        echo $NAME:U6aMy0wojraho |  chpasswd -e ;\
+                        echo \"$NAME ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers "
+}
+        
+start_container() {
+    if [ -z "$1" ]; then 
+        echo "Please supply container name"
+    fi
+    docker run                                          \
+            -v $MOUNT_DIR:$MOUNT_DIR                    \
+            -u ${NAME}                                  \
+            --name $container_name                      \
+            -v $VPP_DIR:/vpp                            \
+            -v /var/run/docker.sock:/var/run/docker.sock\
+            -td $DOCKER_IMAGE_NAME                      \
+            /bin/bash 
+}
+
+
+connect_container() {
+    if [ -z "$1" ]; then 
+                echo "Please supply container name"
+    fi
+    export container_name=$1
+    docker exec -u $NAME -it $container_name  "/bin/bash"
+}
+
+
+stop_container() {
+    if [ -z "$1" ]; then 
+                echo "Please supply container name"
+    fi
+    export container_name=$1
+    docker stop  --name $container_name 
+}
+
+
+
+VPP_DIR=$WORKSPACE/vpp/
+DOCKER_IMAGE="granjan/vpp-build-env:four"
+mkdir -p  $WORKSPACE
+VPP_WS="/home/${CALLER_USER}/VPP-WS/"
+VPP_WS_KITCHEN="KITCHEN"
+export KITCHEN="$WORKSPACE/$VPP_WS_KITCHEN"
+export MOUNT_DIR=$MOUNT_DIR
+export VPP_DIR=$VPP_DIR 
 export NAME=$CALLER_USER
 export uid=$uid
 export gid=$gid
+export DOCKER_IMAGE_NAME=granjan/vpp-build-env:four
+mkdir -p $KITCHEN
+chown $uid:$gid $KITCHEN
+#Copy important files to the kitchen 
+if [ $create_builder -eq 1 ]; then
+    remove_container "builder"
+    create_container "builder"
 
-echo 
-echo "  Removing any build any older build environment"
-docker stop  builder
-docker rm    builder
-docker run \
-    --privileged \
-    -v $VPP_WS:$VPP_WS  \
-    -v /var/run/docker.sock:/var/run/docker.sock \
-    --name builder \
-    -td $DOCKER_IMAGE   \
-    /bin/bash 
-      
+fi
 
-echo "  Removing fixing the image ...."
-docker exec -it builder /bin/bash -c " \
-                  mkdir -p  /home/gyan;\
-                  touch /etc/passwd;\
-                  touch /etc/group; \
-                  groupadd $gid;  \
-                  hostname builder;  \
-                  useradd -rm -d /home/$NAME -s /bin/bash -g $gid  -G sudo  -u $uid $NAME;\
-                  chown $uid:$gid /home/$NAME; \
-                  echo $NAME:U6aMy0wojraho |  chpasswd -e ;\
-                  echo \"$NAME ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers "
+if [ $start_builder -eq 1 ]; then
+    start_container "builder"
+fi
 
-echo "  netns exopsed ...."
-pid=`docker inspect -f '{{.State.Pid}}' builder`
-mkdir -p /var/run/netns/
-rm -f /var/run/netns/builder
-ln -s "/proc/$pid/ns/net" /var/run/netns/builder
 
+if [ $pause_builder -eq 1 ]; then
+    stop_container "builder"
+fi
+
+
+if [ $delete_builder -eq 1 ]; then
+    remove_container "builder"
+fi
+
+if [ $connect_builder -eq 1 ]; then
+    connect_container  "builder"
+fi
+
+ 
diff --git a/launch_test_bot b/launch_test_bot
--- a/launch_test_bot
+++ b/launch_test_bot
@@ -5,12 +5,12 @@ then
     CALLER_USER=`whoami`  
     uid=$(id -u ${CALLER_USER})
     gid=$(id -g ${CALLER_USER})
-    sudo gid=$gid uid=$uid VPP_WS_DIR=$VPP_WS_DIR  CALLER_USER=${CALLER_USER} "$0" "$@"
+    sudo gid=$gid uid=$uid   CALLER_USER=${CALLER_USER} WORKSPACE=${WORKSPACE} "$0" "$@"
     exit
 else
     if [ -z "$CALLER_USER" ]
     then 
-        echo "****** please do not use root account"
+        echo "****** Please do not run as  root "
         exit
     fi
 fi
@@ -19,53 +19,100 @@ fi
 #
 #+-----------+               ------------+                   ------------+
 #|           |    sity12      |           |       sity23     |           |
-#|  sity-1   |----------------+ sity-2    +------------------+   sity-n  |
-#|           |                |           |                  |           |
-#|+---+------+                |+---+------+                  |+----+-----+
-#     |                            |                               |
-#    b|         bsity2             |                               |
-#    s|   +------------------------+                               |
-#    i|   |                                                        |
-#    t|   |           bsity3                                       |
-#    y|   | +------------------------------------------------------+
-#    1|   | |
-#-----+---+-++
-#|           |
-#| builder   |
-#|           |
-#|+----------+
+#|  sity-1   |----------------+ sity-2    +------------------+   sity-n  |----
+#|           |                |           |                  |           |   |
+#|+---+------+                |+---+------+                  |+----+-----+   |
+#     |                                                                      +
+#     -----------------------------------------------------------------------+
 
-#create veth pairs for inter-container 
-#and one for builder that may act as the host
-#container_count=0 
-#while [ $container_count -le $number_of_containers ]
-#do
-#	ip link add name veth_$container_to_container_prefix  type veth peer name $container_to_container_prefix
-#	ip link add name veth_$container_to_builder_prefix  type veth peer name $container_to_builder_prefix
-#done
 
-echo $VPP_WS_DIR 
-echo  $uid $gid  ${CALLER_USER}
-
-#TODO
+#TOD0
+INSTALLATION_PATH="/usr/local/bin/vpp_test_topo"
 INSTALLATION_MODE=1
 #copy ssh-id and misc
-if [ "$(readlink -f $0)" == "/usr/bin/vpp_test_topo_create" ]
+if [ ! "$(readlink -f $0)" == "$INSTALLATION_PATH" ]
 then
+    echo "  Installing in $(readlink -f $0)   $INSTALLATION_PATH"
+    cp "$(readlink -f $0)"  $INSTALLATION_PATH
     INSTALLATION_MODE=0
+    exit
 fi
 
-#we mount the entire home directory
-MOUNT_DIR="/home/${CALLER_USER}/WS/"
+if [ -z "$WORKSPACE" ];
+then
+	echo "  Please export WORKSPACE directory which has build env as well"
+	exit
+else
+	MOUNT_DIR=$WORKSPACE
+fi
 
-#test if vpp is already built ?
+
+VPP_DIR=$WORKSPACE/vpp/
+#check if vpp packages are available in the package director 
+if [ ! -d "$VPP_DIR" ]; then
+	echo "  Please ensure vpp is built and packages are available in $VPP_DIR"
+	  # Control will enter here if $DIRECTORY exists.
+	exit
+fi
+
+
+create_topology=0
+start_topology=0
+pause_topology=0
+delete_topology=0
+connect_topology=0
+index_to_connect=0
+
+# read the options
+OPTION=`getopt -o cspdhn: --long create,start,pause,delete,help,connect: -- "$@"`
+eval set -- "$OPTION"
+#Following are the options 
+while true; do
+    case "$1" in
+        -c| --create ) 
+            create_topology=1
+            shift;;
+        -i| --start )
+            start_topology=1
+            shift;;
+        -n|--connect)
+            connect_topology=1
+            index_to_connect=$2 
+            shift 2;;
+        -s|--pause) 
+            pause_topology=1 
+            shift;;
+        -d|--delete)
+            delete_topology=1
+            shift;;
+        -h|--help) 
+            echo "Usage"
+            echo "      $0  --create          :Create the topology "   
+            echo "      $0  --start           :Starts the topology "
+            echo "      $0  --connect <n>     :Connect to the topology "
+            echo "      $0  --delete          :Delete the topology "
+            echo "      $0  --pause           :Stop the topology  "
+            exit ;;
+        --) shift ; break ;;
+        *) echo "Internal error!" ; exit 1 ;;
+    esac
+done
+
+#echo $create_topology
+#echo $start_topology
+#echo $pause_topology
+#echo $delete_topology
+#echo $connect_topology
+#echo $index_to_connect 
+#
+#exit
 
 export MOUNT_DIR=$MOUNT_DIR
-export VPP_WS_DIR=$VPP_WS_DIR 
+export VPP_DIR=$VPP_DIR 
 export NAME=$CALLER_USER
 export uid=$uid
 export gid=$gid
-host_name="builder"
+export DOCKER_IMAGE_NAME=granjan/vpp-build-env:four
 test_container_prefix="sity"
 max_container=2
 
@@ -77,7 +124,7 @@ expose_container () {
         pid=`docker inspect -f '{{.State.Pid}}' $1`
         rm -rf /var/run/netns/$1
         ln -s /proc/$pid/ns/net /var/run/netns/$1
-        echo "netns of ${1} exposed as /var/run/netns/${1}"
+        echo "     netns of ${1} exposed as /var/run/netns/${1}"
    return 0
 }
 
@@ -87,28 +134,29 @@ remove_container () {
 		echo "Please supply container name"
         return 1
 	else
-		docker stop $1
-		docker rm $1
+		docker stop $1 > /dev/null 2>&1
+		docker rm $1   > /dev/null 2>&1
         return 0
 	fi
 }
 
 create_container() {
-	if [ -z "$1" ]; then 
-		echo "Please supply container name"
-    fi
-	export container_name=$1
-	docker run \
-    	--privileged \
-    	-v $MOUNT_DIR:$MOUNT_DIR  \
-    	--name $container_name \
-        --network none \
-    	-td granjan/vpp-build-env:mini_v1.0  \
-    	/bin/bash 
+        if [ -z "$1" ]; then 
+                echo "Please supply container name"
+        fi
+        export container_name=$1
+        docker run \
+                --privileged \
+                -v $MOUNT_DIR:$MOUNT_DIR  \
+                --name $container_name \
+                -v $VPP_DIR:/vpp  \
+                --network none \
+                -td $DOCKER_IMAGE_NAME  \
+                /bin/bash 
 
-    echo $?
-   	#fix some user name
-	docker exec -it $container_name /bin/bash -c " \
+        echo  fix stuffs in $container_name
+        #fix some user name
+        docker exec -it $container_name /bin/bash -c "\
                   mkdir -p  /home/$NAME;\
                   touch /etc/passwd;\
                   touch /etc/group; \
@@ -117,11 +165,44 @@ create_container() {
                   useradd -rm -d /home/$NAME -s /bin/bash -g $gid  -G sudo  -u $uid $NAME;\
                   chown $uid:$gid /home/$NAME; \
                   echo $NAME:U6aMy0wojraho |  chpasswd -e ;\
-                  dpkg -i $MOUNT_DIR/vpp/build-root/*.deb ;
-                  echo $NAME ALL=(ALL) NOPASSWD:ALL >> /etc/sudoers "
+                  dpkg -i /vpp/build-root/*.deb ;
+                  echo \"$NAME ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers \
                   echo \"dpdk {
                             no-pci
                     }\" >> /etc/vpp/startup.conf "
+        }
+        
+start_container() {
+    if [ -z "$1" ]; then 
+                echo "Please supply container name"
+    fi
+    export container_name=$1
+    docker run \
+                --privileged \
+                -v $MOUNT_DIR:$MOUNT_DIR  \
+                --name $container_name \
+                -v $VPP_DIR:/vpp  \
+                --network none \
+                -td $DOCKER_IMAGE_NAME  \
+                /bin/bash 
+}
+
+
+connect_container() {
+    if [ -z "$1" ]; then 
+                echo "Please supply container name"
+    fi
+    export container_name=$1
+    docker exec -it $container_name  "/bin/bash"
+}
+
+
+stop_container() {
+    if [ -z "$1" ]; then 
+                echo "Please supply container name"
+    fi
+    export container_name=$1
+    docker stop  --name $container_name 
 }
 
 create_veth_and_attach_to_netns()
@@ -138,47 +219,72 @@ delete_veth()
 {
     echo  $1 $2 $3 $4
     ip link delete dev $2  > /dev/null 2>&1
-    ip link delete dev $4444  > /dev/null 2>&1
+    sleep 1
+    ip link delete dev $4  > /dev/null 2>&1
+    sleep 2
     return 0
 }
 
 
+if [ $connect_topology -eq 1 ];then
+    name="$test_container_prefix$index_to_connect"
+    connect_container   $name
+    exit
+fi
+
+
 #configure the topology
-container_index=0
-while [ "$container_index" -lt "$max_container" ]
+    container_index=0
+    echo "  Max number of containers to be created is $max_container"
+    while [ "$container_index" -lt "$max_container" ] 
     do
         name="$test_container_prefix$container_index"
-        remove_container $name
-        create_container $name
-        expose_container $name
         
-        echo deleteing "builder"$name 
-        delete_veth "builder"$name
-        echo creating
-       create_veth_and_attach_to_netns $name "builder"$name  "builder" $name"builder"
-
-        if [ $container_index -ne 0 ]
-            then
+        if [ $create_topology -eq 1 ] || [ $delete_topology -eq 1 ] ; then 
+            echo "  Deleting old container $name <if present>"
+            remove_container $name > /dev/null 2>&1
+        fi
+        
+        if [ $create_topology -eq 1 ]; then 
+            create_container $name > /dev/null 2>&1
+            echo "  Created new container $name"
+        fi
+        
+        if [ $create_topology -eq 1 ]; then
+            start_topology=1
+        elif  [ $start_topology -eq 1 ]; then  
+            start_container $name > /dev/null 2>&1
+            echo "  Started container $name"
+        fi
+        
+        if [ $start_topology -eq 1 ]; then   
+            expose_container $name /dev/null 2>&1
+        fi
+        
+       
+        #
+        if [ $container_index -ne 0 ]; then
             name_old=$test_container_prefix$((container_index-1))
-            echo deleteing "builder"$name 
-            delete_veth  $name$name_old
-            echo creating
-            echo "create_veth_and_attach_to_netns $name  $name$name_old  $name_old $name_old$name"  
-            create_veth_and_attach_to_netns $name  $name$name_old  $name_old $name_old$name  
+            echo "    Deleting old veth $name$name_old pair <if present>"
+            delete_veth $name  $name$name_old  $name_old $name_old$name > /dev/null 2>&1
+            if [ $start_topology -eq 1 ]; then
+                echo "  Creating veth pair  $name from  $name$name_old  and attaching"
+                create_veth_and_attach_to_netns $name  $name$name_old  $name_old $name_old$name > /dev/null 2>&1
+            fi
+        fi
+        
+        if [ $container_index -eq $((max_container-1)) ]; then
+            name_old=$name
+            name=$test_container_prefix$((1-1))
+            echo "    Deleting old veth $name$name_old pair <if present>"
+            delete_veth  $name  "A"$name$name_old  $name_old "A"$name_old$name > /dev/null 2>&1
+            if [ $start_topology -eq 1 ]; then
+                echo "  Creating veth pair  $name from  $name$name_old  and attaching"
+                create_veth_and_attach_to_netns $name  "A"$name$name_old  $name_old "A"$name_old$name > /dev/null 2>&1
+            fi
+            break;
         fi
         container_index=$((container_index+1))
     done
 
-
-if [ "$INSTALLATION_MODE" -eq 0 ]
-then
-    exit
-fi
-
-cp "$(readlink -f $0)" /usr/bin/vpp_test_topo_create
-echo "docker exec  -it $test_container_prefix\$1 "/bin/bash" "  > /usr/bin/vpp_test_connect
-echo "docker stop $test_container_prefix\$1"  > /usr/bin/vpp_test_stop
-echo "docker rm $test_container_prefix\$1"  > /usr/bin/vpp_test_stop
-chmod 777 /usr/bin/vpp_test_*
-
-
+    
